# ==============================================================================
#  Toolchain file -- master board (STM32G491CET6, Cortex-M4F)
#
#  Owns exactly two things: WHICH compiler, and WHAT CPU it targets. Both are
#  properties of the hardware, so they are the same for any project built for
#  this chip. Everything that is a property of THIS project -- linker script,
#  libc variant, optimisation level, warnings, sources -- lives in
#  CMakeLists.txt and must not appear here.
#
#  The previous version (generated by STM32CubeMX) also set the linker script,
#  --specs=nano.specs and the per-build-type optimisation flags. With a
#  CMakeLists that set them too, the build failed four ways in sequence:
#
#    1. --specs=nano.specs twice   -> "attempt to rename spec 'link' to
#                                      already defined spec 'nano_link'"
#    2. linker script misnamed     -> STM32G491xx_FLASH.ld does not exist;
#                                      the real file is STM32G491CETX_FLASH.ld
#    3. linker script given twice  -> "appears multiple times"
#    4. output named master.elf.elf
#
#  Each was hidden behind the one before it. The fix is not to patch the
#  duplicates but to give every setting exactly one owner.
#
#  Selected by CMakePresets.json; nothing else should reference this file.
# ==============================================================================

set(CMAKE_SYSTEM_NAME           Generic)
set(CMAKE_SYSTEM_PROCESSOR      arm)

# A bare-metal cross-compiler cannot link a test executable for the host, so
# CMake's compiler checks must stop at building a static library.
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# --- Compiler and binutils ----------------------------------------------------
# Resolved from PATH. In CLion that PATH comes from the STM32 CLT toolchain's
# environment file; on the command line, from wherever arm-none-eabi-gcc is
# installed.
set(TOOLCHAIN_PREFIX            arm-none-eabi-)

set(CMAKE_C_COMPILER            ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER          ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER          ${TOOLCHAIN_PREFIX}g++)
set(CMAKE_OBJCOPY               ${TOOLCHAIN_PREFIX}objcopy)
set(CMAKE_SIZE                  ${TOOLCHAIN_PREFIX}size)

# Executables come out as <target>.elf. CMakeLists therefore names the target
# plainly -- add_executable(master ...) -- and gets master.elf.
set(CMAKE_EXECUTABLE_SUFFIX_C   .elf)
set(CMAKE_EXECUTABLE_SUFFIX_CXX .elf)
set(CMAKE_EXECUTABLE_SUFFIX_ASM .elf)

# --- CPU ----------------------------------------------------------------------
# The hard-float ABI is required, not preferred: FreeRTOS's ARM_CM4F port
# saves and restores VFP registers in its context switch, and those
# instructions do not assemble under soft-float.
#
# These must also reach the link line, where GCC uses them to select the
# matching multilib -- the build of newlib compiled for this exact FPU and
# float ABI. CMake already passes CMAKE_C_FLAGS to the link driver, so that
# happens without a separate CMAKE_EXE_LINKER_FLAGS_INIT; adding one would put
# every CPU flag on the link line twice.
set(TARGET_FLAGS "-mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard")

# The *_INIT variables, not CMAKE_C_FLAGS itself. CMake can process a toolchain
# file more than once during configuration, so `set(CMAKE_C_FLAGS
# "${CMAKE_C_FLAGS} ...")` -- which is what the CubeMX version did -- appends
# the flags again on every pass. *_INIT is read once, to seed the cache.
set(CMAKE_C_FLAGS_INIT          "${TARGET_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT        "${TARGET_FLAGS}")
set(CMAKE_ASM_FLAGS_INIT        "${TARGET_FLAGS}")